import os
from dotenv import load_dotenv

load_dotenv()

OPENSEARCH_HOST = os.getenv("OPENSEARCH_HOST")
OPENSEARCH_PORT = os.getenv("OPENSEARCH_PORT")
OPENSEARCH_INDEX = os.getenv("OPENSEARCH_INDEX")
CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
EMBEDDING_MODEL =  os.getenv("EMBEDDING_MODEL_NAME")
OPENSEARCH_USER = os.getenv("OPENSEARCH_USER")
OPENSEARCH_PASSWORD = os.getenv("OPENSEARCH_PASSWORD")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
CLAUDE_MODEL = os.getenv("CLAUDE_MODEL")

TOP_K = os.getenv("TOP_K")
CHUNK_SIZE = os.getenv("CHUNK_SIZE")
CHUNK_OVERLAP = os.getenv("CHUNK_OVERLAP")

config = {
    "OPENSEARCH_HOST": OPENSEARCH_HOST,
    "OPENSEARCH_PORT": OPENSEARCH_PORT,
    "OPENSEARCH_INDEX": OPENSEARCH_INDEX,
    "CLAUDE_API_KEY": CLAUDE_API_KEY,
    "EMBEDDING_MODEL": EMBEDDING_MODEL,
    "OPENSEARCH_USER": OPENSEARCH_USER,
    "OPENSEARCH_PASSWORD": OPENSEARCH_PASSWORD,
    "ANTHROPIC_API_KEY": ANTHROPIC_API_KEY,
    "CLAUDE_MODEL": CLAUDE_MODEL,
    "TOP_K": TOP_K,
    "CHUNK_SIZE": CHUNK_SIZE,
    "CHUNK_OVERLAP": CHUNK_OVERLAP
}